export enum EducationalLevel {
  COLLEGE_1AC = 'COLLEGE_1AC',
  COLLEGE_2AC = 'COLLEGE_2AC',
  COLLEGE_3AC = 'COLLEGE_3AC',
  LYCEE_TC = 'LYCEE_TC',
  LYCEE_1BAC = 'LYCEE_1BAC',
  LYCEE_2BAC = 'LYCEE_2BAC',
  UNIVERSITY = 'UNIVERSITY'
}

export enum Stream {
  TC_LETTRES = 'TC_LETTRES',
  TC_SCIENCES = 'TC_SCIENCES',
  TC_TECHNOLOGIE = 'TC_TECHNOLOGIE',
  SC_MATH_A = 'SC_MATH_A',
  SC_MATH_B = 'SC_MATH_B',
  SC_EXPERIMENTAL = 'SC_EXPERIMENTAL',
  SC_PHYSIQUE = 'SC_PHYSIQUE',
  SC_VIE_TERRE = 'SC_VIE_TERRE',
  SC_ECONOMIE = 'SC_ECONOMIE',
  LETTRES_HUMAINES = 'LETTRES_HUMAINES',
  NONE = 'NONE'
}

export enum LessonStatus {
  DRAFT = 'DRAFT',
  AI_GENERATED = 'AI_GENERATED',
  PUBLISHED = 'PUBLISHED'
}
