import "@/app/globals.css"
import { Inter } from "next/font/google"
import { Metadata } from "next"
// import { MathJaxRegistry } from "@/components/mathjax-registry"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "MathSophos Print View",
  robots: "noindex, nofollow",
}

export default function PrintLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={`${inter.className} min-h-screen bg-white text-black`}>
      <style dangerouslySetInnerHTML={{
        __html: `
          @page {
            size: A4;
            margin: 0;
          }
          
          @media print {
            * {
              print-color-adjust: exact !important;
              -webkit-print-color-adjust: exact !important;
              box-sizing: border-box;
            }
            
            html, body {
              width: 210mm;
              min-height: 297mm;
              margin: 0 !important;
              padding: 0 !important;
              background-color: white !important;
            }
            
            /* Content padding: 0.75cm (7.5mm) from edge */
            /* We use padding on body to push content inside */
            body {
              padding: 7.5mm !important;
              position: relative;
            }
            
            /* Red Box: 0.25cm (2.5mm) from edge */
            /* Border width handled by outline or border, we use fixed div */
            #pdf-border-red {
              position: fixed;
              top: 2.5mm;
              left: 2.5mm;
              right: 2.5mm;
              bottom: 2.5mm;
              border: 1px solid red; /* Adjust thickness as needed, user said "border" */
              z-index: 9999;
              pointer-events: none;
            }

            /* Black Box: 0.5cm (5mm) from edge */
            #pdf-border-black {
              position: fixed;
              top: 5mm;
              left: 5mm;
              right: 5mm;
              bottom: 5mm;
              border: 1px solid black;
              z-index: 9998;
              pointer-events: none;
            }
            
            /* Prevent splitting of important elements */
            img, table, figure, .break-inside-avoid, .katex-display {
              page-break-inside: avoid !important;
              break-inside: avoid !important;
            }

            /* Hide header/footer generated by browser */
            @page {
              margin: 0; 
            }
          }
        `
      }} />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
        integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
        crossOrigin="anonymous"
      />
      <script
        defer
        src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
        integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8"
        crossOrigin="anonymous"
      ></script>
      <script
        defer
        src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
        integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
        crossOrigin="anonymous"
      ></script>
      <script dangerouslySetInnerHTML={{
        __html: `
          document.addEventListener("DOMContentLoaded", function() {
            if (window.renderMathInElement) {
              renderMathInElement(document.body, {
                delimiters: [
                  {left: '$$', right: '$$', display: true},
                  {left: '$', right: '$', display: false},
                  {left: '\\\\(', right: '\\\\)', display: false},
                  {left: '\\\\[', right: '\\\\]', display: true}
                ],
                throwOnError : false
              });
            } else {
               // Fallback if DOMContentLoaded fired before script loaded
               window.onload = function() {
                  if (window.renderMathInElement) {
                    renderMathInElement(document.body, {
                      delimiters: [
                         {left: '$$', right: '$$', display: true},
                         {left: '$', right: '$', display: false},
                         {left: '\\\\(', right: '\\\\)', display: false},
                         {left: '\\\\[', right: '\\\\]', display: true}
                      ],
                      throwOnError : false
                    });
                  }
               }
            }
          });
        `
      }} />
      <div id="pdf-border-red"></div>
      <div id="pdf-border-black"></div>
      {children}
    </div>
  )
}
